### ISSUE TITLE
Improve SAM template

### ISSUE THREAD

**Issue by gruebel** [globaldatanet/cost-reporter#2]
1. Remove the `NoEcho` property, because it is no secret, which SSM Parameter you use. Also add the `Description` property to explain, what it does.
https://github.com/globaldatanet/cost-reporter/blob/f15d3fd64764b917a9038eaa73fe0e5f5c903d1d/template.yaml#L10-L13

2. Those types are `Number`
https://github.com/globaldatanet/cost-reporter/blob/f15d3fd64764b917a9038eaa73fe0e5f5c903d1d/template.yaml#L18-L25

3. If this parameter is supposed to be of type boolean, then also enforce it
https://github.com/globaldatanet/cost-reporter/blob/f15d3fd64764b917a9038eaa73fe0e5f5c903d1d/template.yaml#L26-L29
```
  OnlyNotifyOnIncrease:
    Type: String
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Whether to only notify if cost increased within the last day"
```

4. Instead of adding the `logs` permissions
https://github.com/globaldatanet/cost-reporter/blob/f15d3fd64764b917a9038eaa73fe0e5f5c903d1d/template.yaml#L85-L92
just assign the AWS managed policy `arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole`
